Sentinel 1 GRD example
developmentseed/amazon-asdi pull request #2
Opened 2023-01-11 04:01 UTC by rbavery

@wildintellect this example shows how to read and plot Sentinel-1 GRD. So far it's still dealing with VV but I'll add a VH plot and description oh what each band is good for.

This nb shows:
* specifying requester pays
* applying GCP points to warp the S1 image to ground view instead of sar view
* applying an overview level to get a low res version of the image for quick plotting.

2023-01-12 23:47 UTC, wildintellect commented
@rbavery should we have @kathrynberger review the notebook too for a different perspective?

2023-01-13 00:02 UTC, wildintellect commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>While true, when in <code>conda</code> , <code>conda</code> is always preferred over <code>pip</code> for repeatability and consistency. Not sure this is critical information to users of this example.</p><p> </p><p> </p><p>Should we mention this tutorial is meant to work with <code>pangeo-notebook</code> image? </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/developmentseed/amazon-asdi/pull/2/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2023-01-13 00:02 UTC, wildintellect commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>By contrast pystac_client is installed with <code>pip</code> because it's not yet available in <code>conda</code></p><p>Odd -q is used but the code chunk output is verbose, was it cleared and re-run after adding -q?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/developmentseed/amazon-asdi/pull/2/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2023-01-13 00:02 UTC, wildintellect commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>sus -&gt; us</p><p> </p><p>This looks like leftovers from the GLO-30 example</p><p>"Since the DEM data for Sentinel-1 GRD was collected at the same time,"</p><p>We should be able to specify a time window on Sentinel-1</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/developmentseed/amazon-asdi/pull/2/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2023-01-13 00:02 UTC, wildintellect commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>Should we mention, that this data is in eu-central-1 at the top, along with the note about pangeo-notebook so all the recommended things are known upfront.</p><p> </p><p>SSD, or EFS drive (pretty sure Sagemaker uses EFS)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/developmentseed/amazon-asdi/pull/2/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2023-01-13 00:02 UTC, wildintellect commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>Add Note:</p><p>As long as requests are same region, requesters are only paying for GETs, not cross region data transfer or egress.</p><p> </p><p>Add Note:</p><p>How to tell it's a requester pays? Aside from looking at the dataset homepage is it in the STAC info itself?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/developmentseed/amazon-asdi/pull/2/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2023-01-13 00:02 UTC, wildintellect commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>Should we include BBOX limited read to pull partial data?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/developmentseed/amazon-asdi/pull/2/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2023-01-13 00:34 UTC, rbavery commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>sure I can remove this tidbit. and yeah I'll mention that</p>

2023-01-13 00:35 UTC, rbavery commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>no I'm finding that -q doesn't do anything even though the docs indicate it should. so maybe we just keep it verbose?</p>

2023-01-13 00:35 UTC, rbavery commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>ah woops thought I caught all those, will revise</p>

2023-01-13 00:36 UTC, rbavery commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>I'll note this up top. I'm not sure what an EFS drive is but will link to it</p>

2023-01-13 00:40 UTC, rbavery commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>pretty sure it is not in the STAC info. I would guess not since the STAC info is supposed to just list providers and then the rest of the data is agnostic to the provider right?</p><p> </p><p>for example, providers are listed but not if they are requester pays: https://stacindex.org/catalogs/sentinel-1-rtc-conus#/</p><p> </p><p>from the docs:</p><p> </p><p>https://github.com/radiantearth/stac-spec/blob/789e90fba4c7119bc925d26f75f47bacf44c91e6/best-practices.md#requester-pays</p><p> </p><p>"STAC-specific tools in turn can look for the cloud-specific protocols and know to use the requestor pays feature for that specific cloud platform."</p>

2023-01-13 01:35 UTC, rbavery commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>Yeah I can. maybe we only need one example notebook to show that.</p>

2023-01-13 01:35 UTC, rbavery commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>ah nope, just reran and this works</p>

2023-01-13 01:53 UTC, rbavery commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>conda -q does not</p>

2023-01-13 20:11 UTC, rbavery commented
> @rbavery should we have @kathrynberger review the notebook too for a different perspective?

sure I requested a review and addressed your first pass of comments.

2023-01-13 20:50 UTC, wildintellect commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
<p>https://hub.docker.com/r/pangeo/pangeo-notebook , but we probably need to link to AWS instructions for adding an image to Sagemaker https://aws.amazon.com/blogs/machine-learning/bringing-your-own-custom-container-image-to-amazon-sagemaker-studio-notebooks/</p><p> </p><p>Typo <code>bucke tis</code> -&gt; <code>bucket is</code></p><p> </p><p>put the notes inside a markdown Note block with <code>&gt;</code> </p><p>example</p><blockquote><code>&gt; Note: this is a note</code></blockquote>
<br/>

 _Reply via <a href='https://app.reviewnb.com/developmentseed/amazon-asdi/pull/2/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2023-01-16 13:49 UTC, kathrynberger commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
additional typo `pag eon` -> `page on` just a couple lines down from above.

2023-01-16 13:53 UTC, kathrynberger commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +    "This notebook is expected to be run in a the pangeo-notebook image, which can be accessed here: https://hub.docker.com/u/pangeo\n",
Might put pangeo-notebook in quotes here, as the page links to quite a few docker images - some base notebooks, some ML notebooks, so I'd just make it explicitly clear to aid the reader and find the correct one.

2023-01-16 14:17 UTC, kathrynberger commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +    "Feel free to experiment with selecting different overview levels or omitting the overview level argument to read the full native resolution. Before doing so, not that Sentinel-1 images are huge!
typo `not` -> `note`

2023-01-16 14:25 UTC, kathrynberger commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjoAAAHFCAYAAAD7ZFORAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjYuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8o6BhiAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
Move this section up to the top to give context. For the uninitiated, jumping into VV and VH will make less sense - as they don't know why they are using them and why it is important. If you move the last paragraph closer to the top, it can provide context for what these variables are and why we are interested in visualizing them. Otherwise, the sentence prior mentioning Challilo lake comes as a surprise.

2023-01-16 14:27 UTC, kathrynberger commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
> https://hub.docker.com/r/pangeo/pangeo-notebook , but we probably need to link to AWS instructions for adding an image to Sagemaker https://aws.amazon.com/blogs/machine-learning/bringing-your-own-custom-container-image-to-amazon-sagemaker-studio-notebooks/

+1 to @wildintellect's comment.

2023-01-16 14:51 UTC, kathrynberger requested changes
LGTM! I've only made a few minor revisions and suggestions for ease of use/interpretation. Otherwise looks great. 

edit (18/01/2023): I've since tested this on SageMaker too and it works very well. Looks good to me.

2023-01-18 14:43 UTC, kathrynberger commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjoAAAHFCAYAAAD7ZFORAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjYuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8o6BhiAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
In reference to my comments in the notebook code (in case it is note clear above) refers to the text: 

"VH" refers to vertical waves transmitted, horizontal waves received and "VV" refers to vertical waves transmitted, vertical waves received. Different surfaces have different scattering properties that can affect the polarization of the transmitted signal, which Sentinel-1 can detect. To learn more about how to use the VV and VH bands in agriculture, ocean monitoring, forestry, and other earth science applications, check out the [Sentinel-1 product overview page](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-overview/polarimetry) which lists resources."  

In the last portion of the nb text, it would make sense to move this close to the introduction at the top of the nb

2023-01-26 16:02 UTC, rbavery commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +{
thanks!

2023-01-26 16:05 UTC, rbavery commented on examples/sentinel-1/sentinel-1-stac-example.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjoAAAHFCAYAAAD7ZFORAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjYuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8o6BhiAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
great tip, moved it up to the top intro section.

2023-02-07 17:01 UTC, wildintellect commented
This is waiting on us figuring out where the final home of the notebook should be. A new ticket should be opened for any improvements or porting to SageMakerStudioLab.

2023-03-28 23:36 UTC, wildintellect commented
Notebooks have been moved to https://github.com/developmentseed/asdi-examples

2023-03-28 23:36 UTC, closed without merging